before:
  hooks:
    - go mod tidy
project_name: stale-sts-pvc-cleaner
builds:
  - main: './main.go'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
dockers:
  - image_templates:
    - 'ksraj123/state-sts-pvc-cleaner:latest'
    - 'ksraj123/state-sts-pvc-cleaner:{{ .Tag }}'
    dockerfile: Dockerfile.release
  
archives:
  - replacements:
      darwin: macOs
      linux: Linux
      windows: Windows
      amd64: x86_64
changelog:
  sort: asc
  filters:
    exclude:
      - 'Merge pull request'
      - 'Merge branch'
      - '^docs:'
      - '^test:'
