apiVersion: batch/v1 
kind: Job 
metadata:   
  name: lister-sa-job   
  labels:     
    jobgroup: lister-sa 
spec:   
  template:     
    metadata:       
      name: lister-sa       
      labels:         
        jobgroup: lister-sa     
    spec:       
      serviceAccountName: openebs-maya-operator
      automountServiceAccountToken: true
      containers:
      - name: command-demo-container
        image: lister-sa:0.1
        imagePullPolicy: Never
      restartPolicy: Never
