apiVersion: v1
kind: Pod
metadata:
  name: test-runner
spec:
  containers:
  - name: command-demo-container
    image: ksraj123/sts-pv:0.1.1
    imagePullPolicy: Never
    command: ["sleep"]
    args: ["infinity"]
  restartPolicy: Never
