apiVersion: batch/v1 
kind: Job 
metadata:   
  name: lister-sa-job   
  labels:     
    jobgroup: lister-sa 
spec:   
  template:     
    metadata:       
      name: lister-sa       
      labels:         
        jobgroup: lister-sa     
    spec:       
      serviceAccountName: openebs-maya-operator
      automountServiceAccountToken: true
      containers:
      - name: command-demo-container
        image: ksraj123/stale-sts-pvc-cleaner:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: PROVISIONERS
          value: "openebs.io/local"
        - name: NAMESPACES
          value: "default"
      restartPolicy: Never
