apiVersion: v1
kind: Pod
metadata:
  name: test-runner-sa
spec:
  serviceAccountName: openebs-maya-operator
  automountServiceAccountToken: true
  containers:
  - name: command-demo-container
    image: ksraj123/stale-sts-pvc-cleaner:0.1
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: PROVISIONERS
      value: "openebs.io/local"
    - name: NAMESPACES
      value: "default"
  restartPolicy: Never
