apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-storage-class
  annotations:
    openebs.io/delete-dangling-pvc: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local/"
parameters:
  sts-pvc-selector: sts-pvc
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
