kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv-1
 labels:
  type: local
spec:
 persistentVolumeReclaimPolicy: Delete
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
