name: Integration test
on:
  release:
    types:
      - 'created'
  pull_request:
    branches:
      # perform integration test before merging to master
      - 'master'
    paths-ignore:
      - '*.md'
      - 'proposal/**'
      - 'deploy/**'
      - 'LICENSE'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ksraj123/stale-sts-pvc-cleaner:ci
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.23.2'
          kubernetes version: 'v1.22.3'
          driver: none
          start args: '--install-addons=false'
      - name: Integration test
        run: |
          make integration-test
